/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package biz.solidc.taskmanager.config;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author masayasu
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application {

	public Set<Class<?>> getClasses() {
		return getRestResourceClasses();
	}

	/**
	 * Do not modify this method. It is automatically generated by NetBeans REST support.
	 */
	private Set<Class<?>> getRestResourceClasses() {
		Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
		resources.add(biz.solidc.taskmanager.rest.TaskResource.class);
		resources.add(biz.solidc.taskmanager.rest.TasksResource.class);
		return resources;
	}
	
}
